<?php
/**
 * Created by PhpStorm.
 * User: abc
 * Date: 2018/3/29
 * Time: 11:04
 */

namespace app\admin\controller;

use app\common\controller\Admin;
use app\common\model\Ce as CeModel;
use think\Image;

class Ce extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!in_array("03",$this->userinfo['roleary'])) $this->error('没有权限');
    }
    public function index()
    {
        $info=db('Ce')->order('id desc')->paginate(5,false,['query'=>request()->param()]);
        $this->assign("list",$info);
        return $this->fetch();
    }
    function edit(){
        if($this->request->isPost()){
            $data=input('post.');

            //文件上传
            $file = $this->request->file('pic');
            if(!empty($file)){
                $oldpicurl='.'.db('Ce')->where(array('id'=>$data['id']))->value('pic');
                $file->validate(['size' =>1024*1024*2, 'ext' => 'jpg,png,gif']);   //2M
                $file->rule('uniqid');
                $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads/ce');
                if ($info) {
                    $data['pic'] = '/uploads/ce/' . $info->getSaveName();
                    pic_suo($data['pic'],false,650,380);
                    if(strlen($oldpicurl)>3&&file_exists($oldpicurl)){
                        @unlink($oldpicurl);
                        @unlink(pic_suo($oldpicurl,true));
                    }
                } else {
                    $this->error($file->getError());
                }
            }

            $mod=new CeModel();
            $mod->validate("Ce.edit")->allowField(true)->isUpdate()->save($data);
            $this->success("修改成功", url("admin/ce/index"),'',0);
        }else{
            $info=db('Ce')->where(array('id'=>input('id', '', 'trim,intval')))->find();
            $this->assign('info',$info);
            return $this->fetch();
        }
    }
    public function add()
    {
        if($this->request->isPost()){
            $data=input('post.');

            //文件上传
            $file = $this->request->file('pic');
            if(!empty($file)){
                $file->validate(['size' =>1024*1024*2, 'ext' => 'jpg,png,gif']);   //2M
                $file->rule('uniqid');
                $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads/ce');
                if ($info) {
                    $data['pic'] = '/uploads/ce/' . $info->getSaveName();
                    pic_suo($data['pic'],false,650,380);
                } else {
                    $this->error($file->getError());
                }
            }

            $mod=new CeModel();
            $result=$mod->add($data);
            if($result !== false){
                $this->success("添加成功", url("admin/ce/index"),'',0);
            }else{
                $this->error($mod->getError());
            }
        }else {
            return $this->fetch();
        }
    }
    public function del(){
        $mod=new CeModel();
        $result=$mod->del(input('id', '', 'trim,intval'));
        if($result==1){
            $this->success("删除成功", url("admin/ce/index"),'',0);
        }else{
            $this->error('删除失败');
        }
    }






    function rep_index(){
        $list=db('CeRep')->order('view asc,id desc')->paginate(10,false,['query'=>request()->param()]);
        $list->each((function($item, $key){
            $item['ce']=db('Ce')->field("id,name")->where(array('id'=>$item["ce_id"]))->find();
            if($item["member_id"]==0){
                $item["member"]['id']=0;
                $item["member"]['username']="未登录用户";
            }else{
                $item["member"]=db('Member')->field("id,username")->where(array('id'=>$item["member_id"]))->find();
                if(empty($item["member"])) {
                    $item["member"]['id'] = 0;
                    $item["member"]['username'] = "用户被删除";
                }
            }
            return $item;
        }));
        $this->assign("list",$list);
        return $this->fetch();
    }
    public function rep_del(){
        $id=input('id', '', 'trim,intval');
        $mod=new CeRep();
        $result=$mod->del($id);

        if($result==1){
            $this->success("删除成功", url("admin/ce/rep_index"),'',0);
        }else{
            $this->error('删除失败');
        }
    }
    public function rep_view(){
        $id=input('id', '', 'trim,intval');
        db("CeRep")->where(array("id"=>$id))->update(array("view"=>1));
        $this->success("操作成功", url("admin/ce/rep_index"),'',0);
    }


}