<?php
/**
 * Created by PhpStorm.
 * User: abc
 * Date: 2018/3/30
 * Time: 15:03
 */

namespace app\admin\controller;

use app\common\controller\Admin;
use app\common\model\Da as DaModel;

class Da extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!in_array("05",$this->userinfo['roleary'])) $this->error('没有权限');
    }
    public function index()
    {
        $where=array();
        $cate=input('cate');
        if(empty($cate)) $cate=0;
        if(!empty($cate)) $where['cate']=$cate;
        $this->assign("cate",$cate);

        $info=db('Da')->where($where)->select();
        $this->assign("list",$info);
        return $this->fetch();
    }
    function edit(){
        if($this->request->isPost()){
            $data=input('post.');
            $validate = validate('Da');
            if(!$validate->scene('edit')->check($data)){
                $this->error($validate->getError());
            }

            //文件上传
            $file = $this->request->file('picfile');
            if(!empty($file)){
                $oldpicurl='.'.db('Da')->where(array('id'=>$data['id']))->value('pic');
                $file->validate(['size' =>1024*1024*2, 'ext' => 'jpg,png,gif']);   //2M
                $file->rule('uniqid');
                $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads/da');
                if ($info) {
                    $data['pic'] = '/uploads/da/' . $info->getSaveName();
                    if(strlen($oldpicurl)>3&&file_exists($oldpicurl)) unlink($oldpicurl);
                } else {
                    $this->error($file->getError());
                }
            }

            $mod=new DaModel();
            $mod->allowField(true)->isUpdate()->save($data);
            $this->success("修改成功", url("admin/da/index"),'',0);
        }else{
            $info=db('Da')->where(array('id'=>input('id', '', 'trim,intval')))->find();
            $this->assign('info',$info);
            return $this->fetch();
        }
    }
    public function add()
    {
        if($this->request->isPost()){
            $data=input('post.');

            $validate = validate('Da');
            if(!$validate->scene('add')->check($data)){
                $this->error($validate->getError());
            }

            //文件上传
            $file = $this->request->file('picfile');
            if(!empty($file)){
                $file->validate(['size' =>1024*1024*2, 'ext' => 'jpg,png,gif']);   //2M
                $file->rule('uniqid');
                $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads/da');
                if ($info) {
                    $data['pic'] = '/uploads/da/' . $info->getSaveName();
                } else {
                    $this->error($file->getError());
                }
            }
            if(empty($data['pic'])) $data['pic']='';

            $mod=new DaModel();
            $result=$mod->add($data);
            if($result !== false){
                $this->success("添加成功", url("admin/da/index"),'',0);
            }else{
                $this->error($mod->getError());
            }
        }else{
            return $this->fetch();
        }
    }
    public function del(){
        $id=input('id', '', 'trim,intval');
        $mod=new DaModel();
        $result=$mod->del($id);

        if($result==1){
            $this->success("删除成功", url("admin/da/index"),'',0);
        }else{
            $this->error('删除失败');
        }
    }
}