<?php
/**
 * Created by PhpStorm.
 * User: abc
 * Date: 2018/3/29
 * Time: 11:04
 */

namespace app\admin\controller;

use app\common\controller\Admin;
use app\common\model\Member as MemberModel;
use think\paginator;

class Member extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!in_array("07",$this->userinfo['roleary'])) $this->error('没有权限');
    }
    public function index()
    {
        $where=array();
        $username=input('get.username');
        $this->assign("username",$username);
        if(!empty($username)){
            $where['username']	=	['like','%'.$username.'%'];
        }

        $list=db('Member')->where($where)->order('id desc')->paginate(10,false,['query'=>request()->param()]);
        $this->assign("list",$list);
        return $this->fetch();
    }
    public function state(){
        $id=intval(input('id'));
        if(input('state')=="yes") $state=1;
        if(input('state')=="no") $state=0;

        db('Member')->where(array('id'=>$id))->update(array('state'=>$state));
        $this->success("操作成功", url("admin/member/index"),'',0);
    }
    public function del(){
        $admin=new MemberModel();
        $result=$admin->del(input('id', '', 'trim,intval'));
        if($result){
            $this->success("删除成功", url("admin/member/index"),'',0);
        }else{
            $this->error('删除失败');
        }
    }
}