<?php
/**
 * Created by PhpStorm.
 * User: abc
 * Date: 2018/3/29
 * Time: 11:04
 */

namespace app\admin\controller;

use app\common\controller\Admin;

class Sys extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!in_array("07",$this->userinfo['roleary'])) $this->error('没有权限');
    }
    public function set()
    {
        if($this->request->isPost()){
            $data=input('post.');
            $ser=serialize($data);
            if(empty(db('set')->where(array('tp'=>'set'))->find())){
                db('set')->where(array('tp'=>'set'))->insert(array('tp'=>'set','des'=>$ser));
            }else{
                db('set')->where(array('tp'=>'set'))->update(array('des'=>$ser));
            }
            $this->success("修改成功", url("admin/sys/set"),'',0);
        }else{
            $info=db('set')->where(array('tp'=>'set'))->value('des');
            $info=unserialize($info);
            if(empty($info['title'])) $info['title']='';
            if(empty($info['tel'])) $info['tel']='';
            if(empty($info['tongji'])) $info['tongji']='';
            if(empty($info['icp'])) $info['icp']='';
            $this->assign("info",$info);
            return $this->fetch();
        }
    }
}