<?php
/**
 * Created by PhpStorm.
 * User: abc
 * Date: 2018/3/30
 * Time: 8:43
 */

namespace app\admin\controller;

use app\common\controller\Admin;
use app\common\model\Zhaopin as ZhaopinModel;

class Zhaopin extends Admin{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!in_array("06",$this->userinfo['roleary'])) $this->error('没有权限');
    }
    function index(){
        $where=array();
        $name=input('get.name');
        $this->assign("name",$name);
        if(!empty($name)){
            $where['name']	=	['like','%'.$name.'%'];
        }

        $list=db('Zhaopin')->where($where)->order('id desc')->paginate(10,false,['query'=>request()->param()]);
        $this->assign("list",$list);
        return $this->fetch();
    }
    function edit(){
        if($this->request->isPost()){
            $data=input('post.');
            $validate = validate('Zhaopin');
            if(!$validate->scene('edit')->check($data)){
                $this->error($validate->getError());
            }

            $mod=new ZhaopinModel();
            $mod->allowField(true)->isUpdate()->save($data);
            $this->success("修改成功", url("admin/zhaopin/index"),'',0);
        }else{
            $info=db('Zhaopin')->where(array('id'=>input('id', '', 'trim,intval')))->find();
            $this->assign('info',$info);
            return $this->fetch();
        }
    }
    function add(){
        if($this->request->isPost()){
            $data=input('post.');

            $validate = validate('Zhaopin');
            if(!$validate->scene('add')->check($data)){
                $this->error($validate->getError());
            }

            $mod=new ZhaopinModel();
            $result=$mod->add($data);
            if($result !== false){
                $this->success("添加成功", url("admin/zhaopin/index"),'',0);
            }else{
                $this->error($mod->getError());
            }
        }else{
            return $this->fetch();
        }
    }
    public function del(){
        $id=input('id', '', 'trim,intval');
        $mod=new ZhaopinModel();
        $result=$mod->del($id);

        if($result==1){
            $this->success("删除成功", url("admin/zhaopin/index"),'',0);
        }else{
            $this->error('删除失败');
        }
    }
}