<?php
/**
 * Created by PhpStorm.
 * User: sunwen
 * Date: 2018/3/19
 * Time: 16:11
 */
namespace app\common\controller;

use app\common\model\Member;
use think\Controller;

Class Defa extends Controller
{
    public $islogin;
    public $memberinfo;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $info=db('set')->where(array('tp'=>'set'))->value('des');
        $sysinfo=unserialize($info);

        //是否登录
        $member=new Member();
        if($member->cookiecheck()){
            $this->assign("islogin","yes");
            $this->memberinfo=db("Member")->where(array("id"=>cookie('member_uid')))->find();
            $this->assign("memberinfo",$this->memberinfo);
            $this->islogin=true;
        }else{
            $this->assign("islogin","no");
            $this->islogin=false;
        }

        $this->assign("sysinfo",$sysinfo);

        $link=db('Link')->order('id desc')->limit(8)->select();
        $this->assign("link",$link);

        $count=db('set')->where(array('tp'=>'index'))->value('des');
        $count=unserialize($count);
        $this->assign("count",$count);
    }
}